### ISSUE TITLE
Sign/Validate no longer works with PDF upload.

### ISSUE THREAD

**Issue by erikwii** [lsnepomuceno/laravel-a1-pdf-sign#11]
Hello @lsnepomuceno  my code is no longer works after the update to 0.0.6

I think it is since you add checking for pdf file extension [in this commit](https://github.com/lsnepomuceno/laravel-a1-pdf-sign/commit/529394d24fe55104b5f8fd93e2e12294b487fe26)

Previously I can use
```php
$pdf = new SignaturePdf($request->file('file'), $cert, SignaturePdf::MODE_DOWNLOAD);
```
Your code was supported to use a pdf file from upload.

Please let me know if there is another way to do so.
Thanks

**Comment by lsnepomuceno** [comment]
Good morning @erikwii ,

 Signing by uploaded files turned out to be a positive side effect, we hadn't anticipated that directly uploaded files would be signed.

We removed the exception and the behavior was normalized in version [0.0.7](https://github.com/lsnepomuceno/laravel-a1-pdf-sign/releases/tag/0.0.7)

Thanks for the feedback.
